### ISSUE TITLE
ZSH completion doesn't appear to work

### ISSUE THREAD

**Issue by kenzierocks** [erkin/ponysay#219]
It's on my `$fpath` and seems to contain everything, but completions never work. Perhaps this should be looked in to?

**Comment by jristz** [comment]
I remember that @maandree do something eith completions but I was not 100 %
sure what exactly was done.

Maybe Maandree'll explain how completions work and how not??

2015-04-02 22:31 GMT-03:00 Kenzie Togami <notifications@github.com>:

> It's on my $fpath and seems to contain everything, but completions never
> work. Perhaps this should be looked in to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erkin/ponysay/issues/219>.
>



-- 
*Pablo Lezaeta*

**Comment by maandree** [comment]
WTF, github closes issues for you!

It should work now. But you may need to remove `~/.zcompdump`.

**Comment by maandree** [comment]
The completetion scripts for bash, fish and zsh are generated
using auto-auto-complete (whose script is mirrored in ponysay's
source tree to keep it simple). The files `completion/ponysay`
and `completion/ponysay-tool` describe for auto-auto-complete
how ponysay, ponythink and ponysay-tool can be invoked
in a declarative syntax.

zsh did work earlier on, maybe it how it works has changed
because I had to change to top line in the zsh completion scripts
to get it working again. Or I messed something up between version.

(maandree is a unix username, it must be written in lowercase.)

**Comment by kenzierocks** [comment]
Still not working, it seems that the format may have changed? All of [these](https://github.com/zsh-users/zsh-completions/tree/master/src) look different.

**Comment by maandree** [comment]
Seems like there is a bug for the -F option.
Additionally completion is not installed for ponything or ponysay-tool.

I will take a look at these issues.

**Comment by maandree** [comment]
zsh completion for `ponysay` works now, but it very slow and I don't know why.

**Comment by maandree** [comment]
Completion was installed for ponything or ponysay-tool, is checked files installed by pacman what files the installtion installs, so I checked an "old" version (3.0.2) by mistake.

**Comment by jristz** [comment]
Well a2d0360 supposedly fix this I don't get why is open so I will close it.

If still persist ~~consult your medic~~ request for reopen
